### PR TITLE
Secret UI

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
@benjaminapetersen, @jwforres, what do you think of this?  https://raw.githubusercontent.com/rhamilto/angular-key-value-editor/46276b10716323a1db7a6cb2d023488ba36f4acb/docs/key-value-editor-secret-screenshot.png

**Comment by benjaminapetersen** [comment]
Cool, checking it out

**Comment by benjaminapetersen** [comment]
Thinking.  So this is the trigger:
```javascript
entry.containsSecret: true;
```
I wonder if we can do something more generic, like:
```javascript
entry = {
  isReadonly: true,                    // since we have this flag for readonly
  icon: 'fa fa-user-secret',          // if 'icon' exists we can show the icon block
  tooltip: 'My tooltip message',  // if not specified generically on the directive
  displayValue: 'stuff...things?'  // if no entry.value this is a fake value to show...implying secret, etc.
  // the current environment directive has this data structure
  // in place to show this stuff.  We'll need to preserve it even though
  // we don't show it for anything.
  valueFrom: {
    // may have any one of the following:
    configMapKeyRef: {
      key: 'data-1',
      value: 'test'
    },
    secretKeyRef: {   },      // same, key value props
    fieldRef: {   }                // same key, value props
  }
}

```

**Comment by jwforres** [comment]
It feels a little weird that its still an input box and whats in the input
box is a message we are giving you to tell you what its doing...

But :+1: to the icon, thats the one i was talking about

**Comment by rhamilto** [comment]
> It feels a little weird that its still an input box and whats in the input
box is a message we are giving you to tell you what its doing...

I agree.  I explored using a different element and noticed a couple oddities:

* Tabbing through the fields "breaks"; that is, if secret value isn't in a tab, you only press the tab key once to get through the pair containing a secret value.  Not a huge deal, but it was definitely weird.
* The display of long strings became inconsistent;  the input provides a "clipping box" and consistent horizontal "scroll"; I was unable to find a solution that was similar and didn't look really janky.

So I opted to keep the input because it felt less "weird" than the alternatives I was coming up with.

**Comment by rhamilto** [comment]
I think this is ready for merge.

**Pull request merged**
